name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Initialize Sub-modules
      run: |
        git submodule init
        git submodule update

    - name: Autobuild
      uses: github/codeql-action/autobuild@v2

    - name: Run PSEMU
      shell: cmd
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
          cd x64/Release/
          PSEMU.exe
