name: Snyk Scan

on:
  push:
    branches:
      - main

jobs:
  snyk_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup C++
        uses: actions/setup-cxx@v1

      - name: Install dependencies
        run: |
          # Install your C++ dependencies here

      - name: Snyk Scan
        run: npx snyk test --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
